name: flutter_health_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
 
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.0  
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  qr_code_dart_scan: ^0.8.3
  shared_preferences: ^2.2.3
  dio: ^5.7.0
  conditional_builder_null_safety: ^0.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700  